const allMovies = [
    {
        id: 1,
        image: "https://picsum.photos/400/225?random=1",
        title: "Enola Holmesová 2",
        age: "+13",
        tags: "Vtipný * Napínavý * Rodina",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Autem accusantium amet nemo minus quo architecto quas",
    },
    {
        id: 2,
        image: "https://picsum.photos/400/225?random=2",
        title: "Enola Holmesová",
        age: "+13",
        tags: "Vtipný * Napínavý * Rodina",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Autem accusantium amet nemo minus quo architecto quas",
    },
    {
        id: 3,
        image: "https://picsum.photos/400/225?random=3",
        title: "Rocknrolla",
        age: "+16",
        tags: "Gangster * Napínavý * Násilí",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Autem accusantium amet nemo minus quo architecto quas",
    },
    {
        id: 4,
        image: "https://picsum.photos/400/225?random=4",
        title: "Patriot",
        age: "+16",  
        tags: "Gangster * Napínavý * Násilí",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Autem accusantium amet nemo minus quo architecto quas",
    },
    {
        id: 5,
        image: "https://picsum.photos/400/225?random=5",
        title: "Telefon pana Harrigana",
        age: "+16",
        tags: "Gangster * Napínavý * Násilí",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Autem accusantium amet nemo minus quo architecto quas",
    },
    {
        id: 6,
        image: "https://picsum.photos/400/225?random=6",
        title: "Stážista",
        age: "+16",
        tags: "Rodinný * Napínavý * Romantický",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Autem accusantium amet nemo minus quo architecto quas",
    },
    {
        id: 7,
        image: "https://picsum.photos/400/225?random=7",
        title: "Život",
        age: "+13",
        tags: "Vesmír * Napínavý * Nebezpečí",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Autem accusantium amet nemo minus quo architecto quas",
    },
    {
        id: 8,
        image: "https://picsum.photos/400/225?random=8",
        title: "Kód za miliardu dolarů",
        age: "+13",
        tags: "IT * Napínavý",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Autem accusantium amet nemo minus quo architecto quas",
    },
    {
        id: 9,
        image: "https://picsum.photos/400/225?random=9",
        title: "Pracháči",
        age: "+16",
        tags: "Dokument * Napínavý",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Autem accusantium amet nemo minus quo architecto quas",
    },
    {
        id: 10,
        image: "https://picsum.photos/400/225?random=10",
        title: "Whoami",
        age: "+13",
        tags: "Gangster * Napínavý * Násilí",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Autem accusantium amet nemo minus quo architecto quas",
    },
]

export default allMovies
